// Every translatable data-i18n key on zenqor-tech (mirrors translations.en in
// zenqor-tech/script.js) — lets the Website Content > Page Text editor override any
// piece of copy on any zenqor-tech page by writing content/site_text.{key} = {en, ms}.
// Labels are auto-derived from the key name, not hand-curated, so keep this list and
// script.js's translations.en in sync manually if a new key is added there.
export const SITE_TEXT_KEYS = [
    { key: 'nav_home', label: 'Nav Home', group: 'Navigation' },
    { key: 'nav_services', label: 'Nav Services', group: 'Navigation' },
    { key: 'nav_portfolio', label: 'Nav Portfolio', group: 'Navigation' },
    { key: 'nav_about', label: 'Nav About', group: 'Navigation' },
    { key: 'nav_faq', label: 'Nav Faq', group: 'Navigation' },
    { key: 'nav_contact', label: 'Nav Contact', group: 'Navigation' },
    { key: 'nav_port_gaming', label: 'Nav Port Gaming', group: 'Navigation' },
    { key: 'nav_port_web', label: 'Nav Port Web', group: 'Navigation' },
    { key: 'nav_return', label: 'Nav Return', group: 'Navigation' },
    { key: 'nav_legal', label: 'Nav Legal', group: 'Navigation' },
    { key: 'nav_data', label: 'Nav Data', group: 'Navigation' },
    { key: 'hero_badge', label: 'Hero Badge', group: 'Home - Hero & Stats' },
    { key: 'hero_title', label: 'Hero Title', group: 'Home - Hero & Stats' },
    { key: 'hero_sub', label: 'Hero - Subtitle', group: 'Home - Hero & Stats' },
    { key: 'btn_portfolio', label: 'Btn Portfolio', group: 'Home - Hero & Stats' },
    { key: 'btn_contact', label: 'Btn Contact', group: 'Home - Hero & Stats' },
    { key: 'stat_1', label: 'Stat 1', group: 'Home - Hero & Stats' },
    { key: 'stat_2', label: 'Stat 2', group: 'Home - Hero & Stats' },
    { key: 'stat_3', label: 'Stat 3', group: 'Home - Hero & Stats' },
    { key: 'stat_gov', label: 'Stat Gov', group: 'Home - Hero & Stats' },
    { key: 'stat_4', label: 'Stat 4', group: 'Home - Hero & Stats' },
    { key: 'trust_badge_1', label: 'Trust Badge 1', group: 'Home - Hero & Stats' },
    { key: 'trust_badge_2', label: 'Trust Badge 2', group: 'Home - Hero & Stats' },
    { key: 'trust_badge_3', label: 'Trust Badge 3', group: 'Home - Hero & Stats' },
    { key: 'trust_badge_4', label: 'Trust Badge 4', group: 'Home - Hero & Stats' },
    { key: 'testimonials_title', label: 'Testimonials Title', group: 'Home - Testimonials' },
    { key: 'testimonials_sub', label: 'Testimonials - Subtitle', group: 'Home - Testimonials' },
    { key: 'process_title', label: 'Process Title', group: 'Home - How We Work' },
    { key: 'process_sub', label: 'Process - Subtitle', group: 'Home - How We Work' },
    { key: 'process_1_t', label: 'Process 1 - Title', group: 'Home - How We Work' },
    { key: 'process_1_d', label: 'Process 1 - Description', group: 'Home - How We Work' },
    { key: 'process_2_t', label: 'Process 2 - Title', group: 'Home - How We Work' },
    { key: 'process_2_d', label: 'Process 2 - Description', group: 'Home - How We Work' },
    { key: 'process_3_t', label: 'Process 3 - Title', group: 'Home - How We Work' },
    { key: 'process_3_d', label: 'Process 3 - Description', group: 'Home - How We Work' },
    { key: 'process_4_t', label: 'Process 4 - Title', group: 'Home - How We Work' },
    { key: 'process_4_d', label: 'Process 4 - Description', group: 'Home - How We Work' },
    { key: 'process_note', label: 'Process Note', group: 'Home - How We Work' },
    { key: 'cookie_text', label: 'Cookie Text', group: 'Cookie Banner' },
    { key: 'cookie_accept', label: 'Cookie Accept', group: 'Cookie Banner' },
    { key: 'cookie_decline', label: 'Cookie Decline', group: 'Cookie Banner' },
    { key: 'about_title', label: 'About Title', group: 'About Page' },
    { key: 'about_sub', label: 'About - Subtitle', group: 'About Page' },
    { key: 'tech_1', label: 'Tech 1', group: 'About Page' },
    { key: 'tech_2', label: 'Tech 2', group: 'About Page' },
    { key: 'tech_3', label: 'Tech 3', group: 'About Page' },
    { key: 'tech_4', label: 'Tech 4', group: 'About Page' },
    { key: 'tech_1_li1', label: 'Tech 1 - List Item 1', group: 'About Page' },
    { key: 'tech_1_li2', label: 'Tech 1 - List Item 2', group: 'About Page' },
    { key: 'tech_1_li3', label: 'Tech 1 - List Item 3', group: 'About Page' },
    { key: 'tech_2_li1', label: 'Tech 2 - List Item 1', group: 'About Page' },
    { key: 'tech_2_li2', label: 'Tech 2 - List Item 2', group: 'About Page' },
    { key: 'tech_2_li3', label: 'Tech 2 - List Item 3', group: 'About Page' },
    { key: 'tech_3_li1', label: 'Tech 3 - List Item 1', group: 'About Page' },
    { key: 'tech_3_li2', label: 'Tech 3 - List Item 2', group: 'About Page' },
    { key: 'tech_3_li3', label: 'Tech 3 - List Item 3', group: 'About Page' },
    { key: 'tech_4_li1', label: 'Tech 4 - List Item 1', group: 'About Page' },
    { key: 'tech_4_li2', label: 'Tech 4 - List Item 2', group: 'About Page' },
    { key: 'tech_4_li3', label: 'Tech 4 - List Item 3', group: 'About Page' },
    { key: 'agencies_title', label: 'Agencies Title', group: 'About Page' },
    { key: 'agencies_sub', label: 'Agencies - Subtitle', group: 'About Page' },
    { key: 'srv_main_title', label: 'Srv Main Title', group: 'Services Page' },
    { key: 'srv_main_sub', label: 'Srv Main - Subtitle', group: 'Services Page' },
    { key: 'srv_1_t', label: 'Srv 1 - Title', group: 'Services Page' },
    { key: 'srv_1_d', label: 'Srv 1 - Description', group: 'Services Page' },
    { key: 'srv_2_t', label: 'Srv 2 - Title', group: 'Services Page' },
    { key: 'srv_2_d', label: 'Srv 2 - Description', group: 'Services Page' },
    { key: 'srv_3_t', label: 'Srv 3 - Title', group: 'Services Page' },
    { key: 'srv_3_d', label: 'Srv 3 - Description', group: 'Services Page' },
    { key: 'srv_4_t', label: 'Srv 4 - Title', group: 'Services Page' },
    { key: 'srv_4_d', label: 'Srv 4 - Description', group: 'Services Page' },
    { key: 'srv_5_t', label: 'Srv 5 - Title', group: 'Services Page' },
    { key: 'srv_5_d', label: 'Srv 5 - Description', group: 'Services Page' },
    { key: 'srv_6_t', label: 'Srv 6 - Title', group: 'Services Page' },
    { key: 'srv_6_d', label: 'Srv 6 - Description', group: 'Services Page' },
    { key: 'con_title', label: 'Con Title', group: 'Contact Page' },
    { key: 'con_sub', label: 'Con - Subtitle', group: 'Contact Page' },
    { key: 'hq_title', label: 'Hq Title', group: 'Contact Page' },
    { key: 'hq_addr', label: 'Hq Addr', group: 'Contact Page' },
    { key: 'email_caption', label: 'Email Caption', group: 'Contact Page' },
    { key: 'ph_name', label: 'Ph Name', group: 'Contact Page' },
    { key: 'ph_email', label: 'Ph Email', group: 'Contact Page' },
    { key: 'ph_msg', label: 'Ph Msg', group: 'Contact Page' },
    { key: 'ph_phone', label: 'Ph Phone', group: 'Contact Page' },
    { key: 'ph_company', label: 'Ph Company', group: 'Contact Page' },
    { key: 'opt_def', label: 'Opt Def', group: 'Contact Page' },
    { key: 'opt_1', label: 'Opt 1', group: 'Contact Page' },
    { key: 'opt_2', label: 'Opt 2', group: 'Contact Page' },
    { key: 'opt_3', label: 'Opt 3', group: 'Contact Page' },
    { key: 'opt_4', label: 'Opt 4', group: 'Contact Page' },
    { key: 'btn_submit', label: 'Btn Submit', group: 'Contact Page' },
    { key: 'btn_processing', label: 'Btn Processing', group: 'Contact Page' },
    { key: 'biz_hours_title', label: 'Biz Hours Title', group: 'Contact Page' },
    { key: 'biz_hours_weekday', label: 'Biz Hours Weekday', group: 'Contact Page' },
    { key: 'biz_hours_weekend', label: 'Biz Hours Weekend', group: 'Contact Page' },
    { key: 'loading_services', label: 'Loading Services', group: 'Loading / Error Messages' },
    { key: 'loading_portfolio', label: 'Loading Portfolio', group: 'Loading / Error Messages' },
    { key: 'error_db', label: 'Error Db', group: 'Loading / Error Messages' },
    { key: 'faq_page_title', label: 'Faq Page Title', group: 'FAQ Page' },
    { key: 'faq_sub', label: 'Faq - Subtitle', group: 'FAQ Page' },
    { key: 'faq_1_q', label: 'Faq 1 - Question', group: 'FAQ Page' },
    { key: 'faq_1_a', label: 'Faq 1 - Answer', group: 'FAQ Page' },
    { key: 'faq_2_q', label: 'Faq 2 - Question', group: 'FAQ Page' },
    { key: 'faq_2_a', label: 'Faq 2 - Answer', group: 'FAQ Page' },
    { key: 'faq_3_q', label: 'Faq 3 - Question', group: 'FAQ Page' },
    { key: 'faq_3_a', label: 'Faq 3 - Answer', group: 'FAQ Page' },
    { key: 'pg_hero_title', label: 'Pg Hero Title', group: 'Licensing & Permits Page (Hero)' },
    { key: 'pg_hero_sub', label: 'Pg Hero - Subtitle', group: 'Licensing & Permits Page (Hero)' },
    { key: 'tos_content', label: 'Tos Content', group: 'Legal Notices' },
    { key: 'rp_content', label: 'Rp Content', group: 'Return & Refund Policy' },
    { key: 'dp_title', label: 'Dp Title', group: 'Data Policy' },
    { key: 'dp_desc1', label: 'Dp Desc1', group: 'Data Policy' },
    { key: 'dp_desc2', label: 'Dp Desc2', group: 'Data Policy' },
    { key: 'footer_copy', label: 'Footer Copy', group: 'Footer' },
    { key: 'why_badge', label: 'Why Badge', group: 'Home - Why Choose Us' },
    { key: 'why_title', label: 'Why Title', group: 'Home - Why Choose Us' },
    { key: 'why_sub', label: 'Why Sub', group: 'Home - Why Choose Us' },
    { key: 'why_1_t', label: 'Why 1 - Title', group: 'Home - Why Choose Us' },
    { key: 'why_1_d', label: 'Why 1 - Description', group: 'Home - Why Choose Us' },
    { key: 'why_1_li1', label: 'Why 1 - List Item 1', group: 'Home - Why Choose Us' },
    { key: 'why_1_li2', label: 'Why 1 - List Item 2', group: 'Home - Why Choose Us' },
    { key: 'why_1_li3', label: 'Why 1 - List Item 3', group: 'Home - Why Choose Us' },
    { key: 'why_2_t', label: 'Why 2 - Title', group: 'Home - Why Choose Us' },
    { key: 'why_2_d', label: 'Why 2 - Description', group: 'Home - Why Choose Us' },
    { key: 'why_2_note', label: 'Why 2 - Note', group: 'Home - Why Choose Us' },
    { key: 'why_2_li1', label: 'Why 2 - List Item 1', group: 'Home - Why Choose Us' },
    { key: 'why_2_li2', label: 'Why 2 - List Item 2', group: 'Home - Why Choose Us' },
    { key: 'why_2_li3', label: 'Why 2 - List Item 3', group: 'Home - Why Choose Us' },
    { key: 'why_3_t', label: 'Why 3 - Title', group: 'Home - Why Choose Us' },
    { key: 'why_3_d', label: 'Why 3 - Description', group: 'Home - Why Choose Us' },
    { key: 'why_3_tag1', label: 'Why 3 - Tag 1', group: 'Home - Why Choose Us' },
    { key: 'why_3_tag2', label: 'Why 3 - Tag 2', group: 'Home - Why Choose Us' },
    { key: 'why_3_tag3', label: 'Why 3 - Tag 3', group: 'Home - Why Choose Us' },
    { key: 'why_3_tag4', label: 'Why 3 - Tag 4', group: 'Home - Why Choose Us' },
    { key: 'why_3_note', label: 'Why 3 - Note', group: 'Home - Why Choose Us' },
    { key: 'why_3_li1', label: 'Why 3 - List Item 1', group: 'Home - Why Choose Us' },
    { key: 'why_3_li2', label: 'Why 3 - List Item 2', group: 'Home - Why Choose Us' },
    { key: 'why_3_li3', label: 'Why 3 - List Item 3', group: 'Home - Why Choose Us' },
    { key: 'why_4_t', label: 'Why 4 - Title', group: 'Home - Why Choose Us' },
    { key: 'why_4_d', label: 'Why 4 - Description', group: 'Home - Why Choose Us' },
    { key: 'why_4_li1', label: 'Why 4 - List Item 1', group: 'Home - Why Choose Us' },
    { key: 'why_4_li2', label: 'Why 4 - List Item 2', group: 'Home - Why Choose Us' },
    { key: 'why_4_li3', label: 'Why 4 - List Item 3', group: 'Home - Why Choose Us' },
];